### ISSUE TITLE
Roadmap for v1.0

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalafmt#730]
Scalafmt v0.1 came out in March 2016. Here are some stats in January 2017

- 3 maintainers (including myself)
- 40 contributors
- ~10k downloads from Maven last month alone
- ~1k fat jar downloads from github releases last month alone
- IntelliJ plugin is at ~23k downloads in total, with >6k installs on the latest 0.5.x series
- 56 releases (!!)

It's been a really great year, and I'm super thankful for everyone who has been involved in the project so far. I have enjoyed it a LOT and I look forward to continue working on scalafmt.

The formatting output is fairly stable now (big changes like in v0.5.0 to the default style typically provide fallback config for old styles). I think now is a good time to start thinking about releasing v1.0.

I saw somewhere on the interwebs.

> If you want to go quickly, go alone. If you want to go far, go together

I admit it's a bit cheezy, but it does strike a chord with me.

These are organizational things I'd like to get done first

- [x] Move the project under the umbrella of [scala.meta](http://scalameta.org/). I've discussed about this with @xeno-by and we both believe this is a good idea
- [x] Publish under org.scalameta instead of com.geirsson
- [x] Move docs to scalameta.org/scalafmt
- [x] publish docs on merge into master
- [ ] Automatic releases on push tag
- [x] remove unsupported/dangerous options (e.g., bestEffortInDeeplyNestedFunctions, binpack.defnsite)
- [x] #875
I'd be interested to hear what people think.

**Comment by pjrt** [comment]
Something that has been bugging me, and maybe 1.0 is the place to do this: do we want Scalafmt to be a fine-grain or an opinionated, holistic auto-formatting tool?

* The tool started fine-grain: things like how many spaces to indent stuff to and whether to put a new line here or there.
  * Advantage: You can pretty much make your own style
  * Disadvantage: Confusing UI since settings might conflict with one another
* Now we have some settings that throw all of that away and do a holistic approach, like the oddly named `verticalMultilineAtDefinitionSite`.
  * Advantage: It becomes clearer what you code will end up looking like and there are no conflict
  * Disadvantage: If you don't like it, well tough luck. 

Currently we are supporting both of these approaches which can cause even more confusion. I'm on the camp of "full, holistic" reformat where we don't give the option for stuff like how many indents to make on a given closure. Of course we can still support different holistic styles for different sections (`verticalMultilineAtDefinitionSite` vs `binPackedParamGroups` <- made up). But I'm also aware that we will start getting a lot of "why not this!? Please make a setting for this?!".

**Comment by olafurpg** [comment]
That is a great point @pjrt. My view is that scalafmt should be opinionated and provide a unified formatting look across source files. Most users should only have to configure `style = x` and `maxColumn = N` and continue with their lives.

Is there anything in particular that you would like to change to make scalafmt more opinionated/holistic? For example, we could removesome sections from the online configuration docs https://olafurpg.github.io/scalafmt/#Configuration

I would argue that scalafmt is already quite opinionated. The only places where the users controls lines breaks is

- "config style", so it's possible to format argument lists like this

```scala
List(
  1,
  2
)
```

even though it could fit within the max column setting.

- infix applications, after having spent a significant amount of time trying to come up with schemes to automatically chose nice line breaks for infix applications I simply gave up. I still hope to fix this for common operators like `&&`/`+`, but I think it is the right long-term choice for arbitrary DSL operators. I think the AvoidInfix rewrite from @ysusuk helps to minimize unwanted infix operators.

- blank lines, maybe we want to force extra blank lines before top-level methods, but I'm personally leaning towards respecting whatever is in the source.

**Comment by ysusuk** [comment]
you put a great points guys! shall we maybe integrate some monitoring/statistics into scalafmt and find out, if users agree to send us the info, what features/configs are used and hide/remove all unused one?

**Comment by olafurpg** [comment]
@ysusuk although I agree it would be nice to have those statistics, I am not sure the work required to collect the data outweighs the required effort.

**Comment by pjrt** [comment]
The scala style guide recommends `extendSite` to be `2`, we currently have it set to `4` by default.

**Comment by olafurpg** [comment]
I just released v1.0.0 which was identical to v1.0.0-RC4.
